name: CI

on:
  push:
    - 'master'

jobs:
  boot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: make-action
        uses: Qful/make-action@master
        with:
          release: '10-2020-q4'

      - name: build
        run: |
          make all

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: bootloader
      #     path: src/bootloader
